### ISSUE TITLE
Daemon Session

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#13]
The core function which openes #10

**Comment by bensteUEM** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create

**Comment by bensteUEM** [comment]
missing access to library at present 
@WielandF will check with @jan1993

**Comment by bensteUEM** [comment]
@WielandF - we urgently need an update here - didn't know in our call what the latest status is

**Comment by bensteUEM** [comment]
waiting for returns from library

**Comment by WielandF** [comment]
basic coding complete
extended with #67 and #70
