### ISSUE TITLE
How to publish a FF Addon

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#16]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution

**Comment by FrankeA90** [comment]
Add-on should have one of the following formats: .zip, .xpi, .crx, .jar or .xml

**Comment by FrankeA90** [comment]
Upon Upload, certain automatic checks are done by AMO (Addons Mozilla Org).

**Comment by bensteUEM** [comment]
I think the question was originally related to the question who is creating an account, are any signed certificates needed ...

**Comment by bensteUEM** [comment]
@FrankeA90 we need to talk about the details ...

**Comment by FrankeA90** [comment]
@bensteUEM: Account was created, ready for upload

**Comment by bensteUEM** [comment]
@FrankeA90 said we should provide them with a realease zip and he will upload it to moz addon store with the required accounts
