### ISSUE TITLE
Design an Icon

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#17]
For publishing we will need an Icon
for FF the following applies
> If you choose to supply your own icon, It should be 48x48 pixels. You could also supply a 96x96 pixel

**Comment by CaroBa** [comment]
Suggestions for Icons added - 1 bread crumbs or 2 URL-photo 
 Feedback, if feasable?

**Comment by bensteUEM** [comment]
@caro - can you reference your commit here in order to show your suggestions :)

**Comment by CaroBa** [comment]
mystique/4-Admin/bread crumb I.jpg 
 mystique/4-Admin/URL_photo.jpg

**Comment by CaroBa** [comment]
[ mystique/4-Admin/URL_photo.jpg ](url)

**Comment by CaroBa** [comment]
[ mystique/4-Admin/bread crumb I.jpg ](url)
[ mystique/4-Admin/bread crumb II.jpg ](url)

**Comment by bensteUEM** [comment]
@CaroBa - Anhang funktionieren nicht

**Comment by bensteUEM** [comment]
@CaroBa - said the logo is in the admin branch and can be copied

**Comment by belafarinrod91** [comment]
also applied for chrome
