### ISSUE TITLE
Draft a propper project description

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#18]
Create a propper description text which could be used in both FF and Chrome extension descriptions for the stores and addon managers

**Comment by FrankeA90** [comment]
Description draft in English:

[Extension Name - see #35]:
Browse the web while your user profile is obscured by fake activity!

Next-generation anti-tracking tool features:
- Random traffic is generated to obscure your real user profile
- You pick what your profile should look like
- Illegal traffic is prevented by using up-to-date blacklists
- If you have no data flat: define the limit of traffic generated

**********************************************************************
Description draft in German:

[Extension Name - see #35]:
Schütze Deine Privatsphäre mithilfe dieses Addons!

Features dieses Next-Gen Anti-Tracking-Tools:
- Zufallsgenerator erzeugt Fake-Seitenaufrufe
- Du definierst wie Dein Fake-Profil aussehen soll
- Mithilfe einer aktuellen Blacklist werden illegale Seitenbesuche verhindert
- Falls Du keine Daten-Flatrate hast: definiere Dein eigenes Datenlimit!

Any comments?

**Comment by bensteUEM** [comment]
Thanks - triaged into implementation issues for individuel project parts
