### ISSUE TITLE
Persona definieren

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#2]
Als Vorbereitung für Library

**Comment by PatrickP94** [comment]
Can someone check if the actual Persona definition is sufficient or if you need more data/information. If someone has more ideas for potential Personas please add them here.

**Comment by CaroBa** [comment]
DINKS (Karriere, Urlaub, Wellness,  Hochschule, Thermomix, Sushi, Essen gehen, Shopping)
Ingenieur (Studium, VDI, VDA, Elektronik, Maschinenbau, Konstruktion, Zeichnung, Schweißen, Löten, Fügen,  Drehen, Fräsen)
Lehrer (Kinder, Erziehung, Noten, Hausaufgaben, Zeugnisse, Elterngespräch, Schullandheim, Lehrerausflug, Tafel)
Onlineshopper (Zalando, Amazon, DaWanda, Conrad, Notebooksbilliger)
Hundebesitzer (Hundefutter, Hundesteuer, Kotbeutel, Halsband, Hundeleine, Tierarzt)
Bauer (Stall, Rinder, Schweine, Tierarzt, Heu, Weizen, Silo, Mähdrescher, Trecker, Mais)

**Comment by bensteUEM** [comment]
@PatrickP94 danke - das wäre dann wohl jemand aus dem Lib Team 👍
