### ISSUE TITLE
Do we need to filter non http links in DOM inspection?

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#20]
Hi, after implementing isOnSameDomain function for #11 i found that we might also have tel: or other non http links - do we need to filter those or does the library do this?

**Comment by bensteUEM** [comment]
@WielandF will ask @jan1993 tomorrow

**Comment by WielandF** [comment]
Hi, the libary will filter those links. @bensteUEM @jan1993

**Comment by jan1993** [comment]
This should be part of the filtering. Can be integrated in the filter against the BPjM List?
Implemented by @Monti93 ???

**Comment by bensteUEM** [comment]
@Monti93  - you're part of the lib team ? Only issue would be that you would have to request a new link if an invalid link was passed e..g tel: link was selected by random

**Comment by Monti93** [comment]
Hi guys, yes I am part of the team as well. Sorry for the late response, I haven't found enough time for the topic yet. I can include this in the filter.

**Comment by bensteUEM** [comment]
will be fixed in #50
