### ISSUE TITLE
Addon name definition

### ISSUE THREAD

**Issue by FrankeA90** [bensteUEM/mystique#35]
Admin Team (A. Franke, P. Kern) ideas:
- FogUp
- MotherFogger
- Ayautheotl (Aztekische Dunstgottheit)
- Nagual (Aztekisch für Verkleidung)
- FogIt
- TrackThis
- Fog You!

Prof ideas:
-Track my Ass

We need the name first, then we can think about creating an icon  (issue #17)

**Comment by BrueckmannM** [comment]
I would suggest simply stick to the working title "Mystique". I like that one

**Comment by CaroBa** [comment]
"Mytique" is fine for me too. Do we have to consider copyrights?
