### ISSUE TITLE
Insert project description into metadata (FF)

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#37]
followup of #18

**Comment by CaroBa** [comment]
Functionality:
Our extension produces noice, while you are normally surfing the web. In the background different websites will be opened. These websites are random but connected to a specified stereotype.

Key Features:
- Browse the web while your user profile is obscured by fake activity!
- Random traffic is generated to obscure your real user profile!
- You pick what your fake profile should look like!
- Illegal traffic is prevented by using up-to-date blacklists!
- If you have no data flat: define the limit of traffic generated!

**Comment by bensteUEM** [comment]
same here - where has this been applied to the manifest - or is this just a new text

**Comment by CaroBa** [comment]
Link: Website
https://mystique-extension.jimdo.com/

**Comment by bensteUEM** [comment]
```
	"description": "Our extension produces noice, while you are normally surfing the web. In the background different websites will be opened. These websites are random but connected to a specified stereotype.",
	
	"author": "DHBW.CAS.ADM.2K17",
	"homepage_url": "https://mystique-extension.jimdo.com/",
```

**Comment by bensteUEM** [comment]
#38 use updated text from here
