### ISSUE TITLE
BPjM Filter API

### ISSUE THREAD

**Issue by Monti93** [bensteUEM/mystique#39]
Hi @jan1993, @michischeid, 
I am currently watching for BPjM filter APIs or services that give me access to any content. As far as I can see there is no way to consume the BPjM content directly: http://www.bundespruefstelle.de/bpjm/Aufgaben/Listenfuehrung/bpjm-modul.html 
However there is an API from Google called "Safe Browsing" which seems to deliver what we need. The API is open source and the usage of the services are free of charge. But we need a developer key in order to use the service. I don't mind to use my account for developing and testing but for a long-term usage I prefer an official CAS account. How do you feel about this?

**Comment by Monti93** [comment]
BTW... here is the link to the Google API: https://developers.google.com/safe-browsing/

**Comment by michischeid** [comment]
@Monti93  I don't mind either. But for me it is just a project. I don't know if really would like to invest that effort. But feel free to do so.
