### ISSUE TITLE
approveURL Regexp for allowed URLS + blacklist

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#50]
regexp

^https
^http
^../
^./
^/
^javascript

disregard relative links that start with text only
this should be done in the background script in order to make sure 

create for FF and copy later for Chrome

**Comment by bensteUEM** [comment]
function will be implemented in backend using the approveURL() function

**Comment by bensteUEM** [comment]
@Monti93 - safesearch?

**Comment by WielandF** [comment]
//Testing purpose function whitelisting
var wert= "//...dadd"
whiteListing(wert);

/**
* Checks the url if it fits the whitelist conditions to disregard 
* relative links thta start with text only
*	@param url the URL to be checked
*/
function whiteListing(wert){
       const pattern = /(^http)|(^https)|[^/]|[^./]|[^../]|(^javascript)/;
       let match = pattern.exec(wert);
       if (match)
        //ToDo call the openurl function  
		console.log("da");
	  else{
		  //ToDo What happens if the whitelist check is not positive
		  console.log("weg");
	  }
}
