### ISSUE TITLE
Define ranges for Settings

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#53]
* int linkDepth_max 
* int numberOfLinksToClick_max > in %
* int maxVisitTime > in sec

should be rrestricted to a reasonable range
please define allowed values

**Comment by PhK3rn** [comment]
maxVisitTime:random sec 60 - 660
linkDepth_max & numberOfLinksToClick_max are separated in 3 different options, which could be set by user:

**few**: depth_max = 3; nol_max= 20%
**medium**: depth_max = 7; nol_max= 30%
**plenty**: depth_max = 11; nol_max= 40%

**Comment by PhK3rn** [comment]
![crawl wideness-depth](https://cloud.githubusercontent.com/assets/26923917/26202640/6bc4d2dc-3bd8-11e7-9b4d-02d102356aa1.jpg)

**Comment by PhK3rn** [comment]
![crawl wideness-depth](https://cloud.githubusercontent.com/assets/26923917/26202752/da95d774-3bd8-11e7-9b1b-425ace8e47d2.jpg)

**Comment by bensteUEM** [comment]
maxPageviewsFromRoot = 200

**Comment by PhK3rn** [comment]
![bw -- crawl wideness-depth](https://cloud.githubusercontent.com/assets/26923917/26205966/b31fe724-3be3-11e7-8c31-416b44c9f372.jpg)
