### ISSUE TITLE
Display Keywordlist used

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#56]
in settings in order to show the user that something is happening

    Keywords: [
      {word: "DAX", score: 0},
      {word: "Börsenkurs", score: 5},
      {word: "Aktien", score: 10},
      {word: "Wechselkurse", score: 3},
      {word: "Goldpreis", score: 7}
      ],

**Comment by MelanieFroescher** [comment]
Keywords are displayed for the selected persona. Score is not displayed.
