### ISSUE TITLE
Settings headlines and texts have to be aligned between FF and Chrome

### ISSUE THREAD

**Issue by flowtuete** [bensteUEM/mystique#58]

**Comment by bensteUEM** [comment]
included the new fields however naming and style needs to be aligned

**Comment by bensteUEM** [comment]
@FrankeA90  - doku team needs to define the correct wording which should be used in both chrome and ff
https://github.com/bensteUEM/mystique/wiki/Fronend

**Comment by CaroBa** [comment]
Settings defined, settings commited
