### ISSUE TITLE
Cocode LinkLevel Followup

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#62]
The code developed along with the Chrome group which is taking action for following links in the defined schemes leveraging link depth and other random functions needs to be adapted to FF

**Comment by BrueckmannM** [comment]
FF add-on maintains a data structure to keep track of link-following-depth now.
The following things still need to be done / thought of:

- getting initial URL from library
- getting new URL from library when link tree is completely processed
- special handling when an URL cannot be opened (happens from time to time)

**Comment by bensteUEM** [comment]
@BrueckmannM  -fixed or is anthing sitll to be done here?

**Comment by bensteUEM** [comment]
@WielandF - status?

**Comment by WielandF** [comment]
@bensteUEM This issue could be closed!
