### ISSUE TITLE
Do we need a reset button in the GUI

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#64]
if we overwrite the persona keywords we should have a reset button in the GUI.

* do we write added keywords into the current selected persona or are we missing an additional keywords field on the same level as persona?

**Comment by FrankeA90** [comment]
@bensteUEM Yes - implement a "reset to defaults" button in both Firefox & Chrome settings.

Functionality description:
- Once button is pressed, settings are deleted
- and Call to Method "Initialize Config" is done

**Comment by CaroBa** [comment]
Reset button added
