### ISSUE TITLE
Session handling with URL-Library

### ISSUE THREAD

**Issue by BrueckmannM** [bensteUEM/mystique#67]
This point contains the following subtopics:

- initial call to the library for first run of background script
- further calls to library whenever the global URL list is empty
- ensure that the library really returns a URL (sometimes an empty result seems to be returned)
- verification of each link gained from content script

**Comment by BrueckmannM** [comment]
open points:
- insert parameters from config instead of global variables
- include max tree size (view page) recognition
- calculate visit time for each URL call from max/min visit time
- solution for deactivation of plugin

**Comment by bensteUEM** [comment]
this sounds similar to another issue of yours ... max/min time visit time is already included by now

**Comment by BrueckmannM** [comment]
4/4 fixed
