### ISSUE TITLE
Timeout/Interval handling

### ISSUE THREAD

**Issue by BrueckmannM** [bensteUEM/mystique#70]
- read min/max visit time from settings and set up interval/timer handling for opening new URLs after timer has elapsed
- sometimes it happens that we get stuck on a certain URLs - the interval handler should recognize such situations and take appropriate counter measures (e.g remove "broken" URL from global URL list and continue)
- timer cancellation when add-on is deactivated from popup

**Comment by BrueckmannM** [comment]
Set up watchdog timer that ensures that the script keeps running, even if no new links will be received from the content script.

**Comment by bensteUEM** [comment]
usage of timer introduced with 346f97ab1999c82ca6f8dd1af48ca04e538e9ac0 does this already fix the bug or did you want to add anything else for 1st release?

**Comment by BrueckmannM** [comment]
I have taken the code to calculate visit time from 3-Firefox-benste branch and extended it in my last commit 16e0fc5 such that a separate function to provide next visit time value is available now.

**Comment by BrueckmannM** [comment]
remaining open points fixed with commit 078a89c
