### ISSUE TITLE
There is a typo in a urlib variable name

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#78]
https://github.com/bensteUEM/mystique/blob/Lib-master/1-Library/urlLib.js#L329
should be "length" instead of "lenght"
see https://www.merriam-webster.com/dictionary/length

**Comment by Monti93** [comment]
fixed... feel free to change those minor things by yourself instead of opening an issue and wait for answers. This might be faster I guess ;)

**Comment by bensteUEM** [comment]
didn't  want to mess your code - the commit is missing the issue id but i'll follow your text and close the issue.
