### ISSUE TITLE
Frontend - Settings Window

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/mystique#8]
GUI, settings file changes

opened from #7

**Comment by bensteUEM** [comment]
from @MelanieFroescher 
- Settings  page does exist today
- Save and Load of Settings to JSON works 
- Does not use any style library yet

at present the options menu does have an entry which is not working
> mostly done

**Comment by bensteUEM** [comment]
Persona selection is missing at present

**Comment by MelanieFroescher** [comment]
Persona selection added
