### ISSUE TITLE
Value ranges for maxBytes, maxLinkDepth, maxNumberOfLinksToClick (low, medium, high)

### ISSUE THREAD

**Issue by MelanieFroescher** [bensteUEM/mystique#84]
We talked about a DropDown for these settings to allow the user to just select between low, medium, high.
Can someone provide the value ranges that identify low, medium, high?
Maybe this is a global definition...

**Comment by bensteUEM** [comment]
@MelanieFroescher - currently no defaults are selected when opening the current branch - is this intended to behave this way?

**Comment by bensteUEM** [comment]
Check if Chrome implemented non standard , if not define own mapping @MelanieFroescher

**Comment by bensteUEM** [comment]
this also causes the settings to corrupt because at present no values are saved for max%click

**Comment by bensteUEM** [comment]
I've updated your branch - don't forget to sync before you fix this final issue ...

**Comment by MelanieFroescher** [comment]
Done
