### ISSUE TITLE
Filter links by domain seems never to be used

### ISSUE THREAD

**Issue by BrueckmannM** [bensteUEM/mystique#85]
Maybe it's only a problem of my understanding , but I cannot see how and if the function `getLinksDomainPercentage` actually takes the variable `followLinkOnDomainOnly` into consideration?! 
From my point of view only the `getLinksDomain` does really consider that variable, but we don't use that function at all.

Currently for me it seems that we never filter our links by the current domain.

**Comment by bensteUEM** [comment]
will check ...

**Comment by bensteUEM** [comment]
line 135
`		filteredLinksFromCS = getLinksDomainPercentage(message.data,config.settings.followLinkOnDomainOnly,config.settings.maxNumberOfLinksToClick)
`
> line 401
`followLinkOnDomainOnly`
>> some code was changed - its indeed not filtered - before the procedure used getLnksDomain, but now this is part of data.message - needs to be changed
