### ISSUE TITLE
Usage of config object

### ISSUE THREAD

**Issue by BrueckmannM** [bensteUEM/mystique#86]
Is it really correct that we use `urlLib.initializeConfig()` to retrieve a configuration object in the following situations:

- within `getLinksDomainPercentage` when `urlLib.approveURL` is called
- within `sessionHandler` when `urlLib.generateURL` is called

Wouldn't it be correct to provide the configuration from our browser storage instead?

**Comment by bensteUEM** [comment]
likely not - will need to check where this part is executed
