### ISSUE TITLE
ApproveUrls does not filter corectly

### ISSUE THREAD

**Issue by BrueckmannM** [bensteUEM/mystique#91]
Sometimes it happens that the Library does not approve URLs correctly. 
When we gather links like "javascript:void(0)" from a website and send these to the `approveUrl` function they won't be filtered but approved instead. 

By that our FF extension tries to open those links. Obviously this doesn't work.

**Comment by Monti93** [comment]
I fixed the issue in the Lib-master branch. The problem was the regex allowing javascript URLs. It should work now.
